name: CMake

on: workflow_dispatch

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set-env
      run:  VER=`date +"%y.%m%d-%H%M"`;
            BRANCH=`git branch --show-current`;
            echo "FILE_VERSION=${BRANCH}-${VER}" >> $GITHUB_ENV

    - name: Build 
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      # working-directory: ~/XCFlarmView
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12

      run:  touch $PWD/main/Version.h;
            python $PWD/tools/fln2head.py >$PWD/main/flarmnetdata.h;   
            docker run --rm -v $PWD:/project -w /project espressif/idf:release-v4.4 idf.py build;
            mkdir -p artifacts;
            cp $PWD/build/xcflarmview.bin $PWD/artifacts/xcflarmview-${{ env.FILE_VERSION }}.bin;
            cp $PWD/build/xcflarmview.elf $PWD/artifacts/xcflarmview-${{ env.FILE_VERSION }}.elf;
            gzip $PWD/artifacts/xcflarmview-${{ env.FILE_VERSION }}.elf;
            ls artifacts/*;

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: XCFlarmView-${{ env.FILE_VERSION }}
        path: artifacts/xcflarmview-${{ env.FILE_VERSION }}.bin
     
    - name: Upload ELF
      uses: actions/upload-artifact-elf@v4
      with:
        name: XCFlarmView-${{ env.FILE_VERSION }}
        path: artifacts/xcflarmview-${{ env.FILE_VERSION }}.elf.gz
